version: "3"

services:
  serve:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - .:/flask/code
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 5001:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start


    
